evsmms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('kyc.urls')),
    path('service/', include('service.urls')),
    # path('admin/login/', auth_views.LoginView.as_view(template_name='admin/adminlogin.html'), name='login'),
    path('admin/', admin.site.urls),

    path('accounts/', include('kyc.urls')),
]

evsrms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('kyc.urls')),
    path('service/', include('service.urls')),
    # path('admin/login/', auth_views.LoginView.as_view(template_name='admin/adminlogin.html'), name='login'),
    path('admin/', admin.site.urls),

    path('accounts/', include('kyc.urls')),
]

kyc/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'kyc'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),
         name='password_reset_complete'),

]

service/urls.py
from django.urls import path
from . import views

app_name = 'service'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /suggestions/5/
    path('<int:suggestion_id>/', views.detail, name='detail'),
]

suggestions/urls.py
from django.urls import path
from . import views

app_name = 'suggestions'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /service/5/
    path('<int:suggestion_id>/', views.detail, name='detail'),
]

kyc/models.py
from django.db import models


# Create your models here.
class Vehicle(models.Model):
    make = models.CharField(max_length=30)
    model = models.CharField('vehicle_model', max_length=30)
    plate_number = models.CharField('Plate number', max_length=30)
    category = models.CharField(max_length=30)
    status = models.CharField('Operation status', max_length=30)

    def __str__(self):
        return self.plate_number

repair/models.py
import random
import string
from django.db import models
from service.models import Vehicle

# Create your models here.
reference_string = string.ascii_letters + string.digits + string.punctuation


class Ticket(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    ref = models.CharField('Reference', default=''.join(random.sample(reference_string, 10)), max_length=50)
    status = models.CharField('Operation status', max_length=30)
    item_maintained = models.CharField(max_length=30)
    frequency = models.IntegerField(default=0)
    cost = models.IntegerField(default=0)
    date = models.DateTimeField()

    def __str__(self):
        return self.ref

service/models.py
from django.db import models


# Create your models here.
from kyc.models import Vehicle


class ServiceTicket(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    status = models.CharField('Operation status', max_length=30)
    item_serviced = models.CharField(max_length=30)
    frequency = models.IntegerField(default=0)
    cost = models.IntegerField(default=0)
    date = models.DateTimeField()

    def __str__(self):
        return self.item_serviced

suggestions/models.py
from django.db import models


# Create your models here.
from service.models import Vehicle


class Suggestion(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    description = models.CharField('description', max_length=30)

    def __str__(self):
        return self.title

kyc/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse, Http404
from django.shortcuts import render


# Create your views here.


def index(request: WSGIRequest) -> HttpResponse | Http404:
    """
    Homepage view
    Returns the homepage of the system
    """

    return render(request, 'kyc/index.html')

repair/views.py
from django.shortcuts import render

# Create your views here.

service/views.py
from django.conf import settings
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.http import HttpResponse
from .models import Vehicle


# Create your views here.

def index(request: WSGIRequest) -> HttpResponse | Http404:
    """
    Homepage view
    Returns the homepage of the service app
    """
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    latest_vehicle_list = Vehicle.objects.order_by('-make')[:5]

    context = {
        'latest_vehicle_list': latest_vehicle_list,
    }
    return render(request, 'service/index.html', context)


def detail(request: WSGIRequest, vehicle_id: int) -> HttpResponse | Http404:
    """
    Vehicle details
    """
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
    return render(request, 'service/detail.html', {'vehicle': vehicle})

suggestions/views.py
from django.conf import settings
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404
from django.http import HttpResponse
from .models import Suggestion


# Create your views here.

def index(request: WSGIRequest) -> HttpResponse | Http404:
    """
    Homepage view
    Returns the homepage of the suggestions app
    """
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    latest_suggestion_list = Suggestion.objects.order_by('-title')[:5]

    context = {
        'latest_vehicle_list': latest_suggestion_list,
    }
    return render(request, 'suggestions/index.html', context)


def detail(request: WSGIRequest, suggestion_id: int) -> HttpResponse | Http404:
    """
    Suggestion details
    """
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    suggestion = get_object_or_404(Suggestion, pk=suggestion_id)
    return render(request, 'suggestions/detail.html', {'suggestion': suggestion})

kyc/templates/kyc/index.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
    <!-- CSS only
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet">-->
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            background-color: #f1f1f1;
            padding: 20px;
            font-family: Arial, serif;
        }

        /* Center website */
        .main {
            max-width: 1000px;
            margin: auto;
        }

        h1 {
            font-size: 50px;
            word-break: break-all;
        }

        .row {
            margin: 8px -16px;
        }

        /* Add padding BETWEEN each column (if you want) */
        .row,
        .row > .column {
            padding: 8px;
        }

        /* Create four equal columns that floats next to each other */
        .column {
            float: left;
            width: 25%;
        }

        /* Clear floats after rows */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        /* Content */
        .content {
            background-color: white;
            padding: 10px;
        }

        /* Responsive layout - makes a two column-layout instead of four columns */
        @media screen and (max-width: 900px) {
            .column {
                width: 50%;
            }
        }

        /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
            }
        }
    </style>
</head>
<body>

{% block content %}

<div style="margin-left: 200px;">
{% if  user.is_authenticated %}
    <p> {{ user.username }} TODO</p>
    <ul>
        <li><p><a href="{% url 'service:index' %}">Vehicle Services</a></p></li>
        <li><p><a href="{% url 'admin:index' %}">Vehicle Repairs</a></p></li>
        <li><p><a href="{% url 'kyc:logout' %}">Suggestion Box</a></p></li>
    </ul>



{% else %}
    <!-- MAIN (Center website) -->
    <div class="main">
    <div class="flex-container" style="flex-direction: row">
        <div>

        <h2>Electronic Vehicle Service and Repair Management System</h2>
        <hr>
        <div class="content">
            <h2>Vehicle maintenance, redefined!</h2>
            <p>Control vehicle services and repairs,Achieve more profits.</p>
        </div>


        <!-- Users Interface Grid -->
        <div class="row">
            <div class="column">
                <div class="content">
                    <h3><a href="{% url 'admin:index' %}">Fleet Manager</a></h3>
                    <p>Your transportation business needs an intelligent management. </p>
                </div>
            </div>
            <div class="column">
                <div class="content">
                    <h3><a href="{% url 'kyc:login' %}">Driver</a></h3>
                    <p>Put your vehicle in control.</p>
                </div>
            </div>
            <div class="column">
                <div class="content">
                    <h3><a href="https://evsmms.github.io/#getting-started">I'm New Here!</a></h3>
                    <p>Read the documentation, to easily get started.</p>
                </div>
            </div>
            <div class="column">
                <div class="content">
                    <h3><a href="https://evsmms.github.io/">About EVSMMS</a></h3>
                    <p>You deserve more</p>
                    <p> Read why this project exists.</p>
                </div>
            </div>
        </div>
            </div>
    <div>1</div>
  <div>2</div>
  <div>3</div>
    </div>


        <!-- END MAIN -->
    </div>
{% endif %}
<!-- JavaScript Bundle with Popper -->
<script crossorigin="anonymous"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        src="
        https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}
</div>
</body>
</html>

service/templates/service/detail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>{{ vehicle.make }}</title>
</head>
<body>
<h1>Service tickets for {{ vehicle.make }} {{ vehicle.model }}</h1>
</body>
</html>

service/templates/service/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Vehicle Service</title>
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'service/style.css' %}">
</head>
<body>
{% if latest_vehicle_list %}
<ul>
{% for vehicle in latest_vehicle_list %}
<li><a href="{% url 'service:detail' vehicle.id %}">{{ vehicle.make }} {{ vehicle.model }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No service tickets are available.</p>
{% endif %}

</body>
</html>

suggestions/templates/suggestions/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

suggestions/templates/suggestions/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
{% load i18n static %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
<title>{% block title %}oi{% endblock title %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% if not is_popup and is_nav_sidebar_enabled %}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/nav_sidebar.css" %}">
  <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
{% endif %}
{% block extrastyle %}{% endblock extrastyle %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock stylesheet_rtl %}">{% endif %}
{% block extrahead %}{% endblock extrahead %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock responsive %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock blockbots %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}EVSMMS{% endblock branding %}
        </div>
        {% block usertools %}
        {% if request.user.is_authenticated %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% translate 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock welcome-msg %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% translate 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                    {% if user.is_staff %}
                    <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
                        {% else %}
                         <a href="{% url 'kyc:password_change' %}">{% translate 'Change password' %}</a> /
                    {% endif %} 

                {% endif %}
                {% if user.is_staff %}
                <a href="{% url 'admin:logout' %}">{% translate 'Log out' %}</a>
                    {% else %}
                    <a href="{% url 'kyc:logout' %}">{% translate 'Log out' %}</a>
                {% endif %}
            {% endblock userlinks %}
        </div>
        {% endif %}
        {% endblock usertools%}
        {% block nav-global %}{% endblock nav-global%}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'kyc:index' %}">{% translate 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock breadcrumbs%}
    {% endif %}

    <div class="main shifted" id="main">
      {% if not is_popup and is_nav_sidebar_enabled %}
        {% block nav-sidebar %}
          {% include "admin/nav_sidebar.html" %}
        {% endblock nav-sidebar%}
      {% endif %}
      <div class="content">
        {% block messages %}
          {% if messages %}
            <ul class="messagelist">{% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
            {% endfor %}</ul>
          {% endif %}
        {% endblock messages %}
        <!-- Content -->
        <div id="content" class="{% block coltype %}colM{% endblock %}">
          {% block pretitle %}{% endblock pretitle%}
          {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock content_title%}
          {% block content_subtitle %}{% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}{% endblock content_subtitle%}
          {% block content %}
            {% block object-tools %}{% endblock object-tools%}
            {{ content }}
          {% endblock content%}
          {% block sidebar %}{% endblock sidebar%}
          <br class="clear">
        </div>
        <!-- END Content -->
        {% block footer %}<div id="footer"><div style="text-align: center">
            <p>Crafted with <span style="color:red;">&hearts;</span> from University of Dar es Salaam.</p>
    <p><a href="https://github.com/evsmms/evmms/tree/v0.0.0-alpha">v0.0.0-alpha</a>
        <strong>&copy;2021-
            <script>document.write(new Date().getFullYear().toString());</script>
            <a href="https://evsmms.github.io" title="Evsmms Software">
                Evsmms&#153 Software</a>
        </strong>
    </p>
    <p> Some rights reserved.</p>
            <a href="https://www.djangoproject.com/">
                <img src="https://www.djangoproject.com/m/img/badges/djangomade124x25.gif"
                     style="border: #003366;" alt="Made with Django." title="Made with Django." />
            </a>
</div>
</div>{% endblock footer%}
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

templates/password/password_reset.html
{%extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}

	<!--Reset Password-->
	<div class="container p-5" style="text-align: center">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Send email</button>
            <br/>
            <p><button class="btn btn-primary" ><a href="{% url 'kyc:login' %}">Go Back to Login</a></button></p>
        </form>
  	</div>

{% endblock %}

templates/password/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "base.html" %}

{% block content %}

  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <a href="/login" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}
</body>
</html>